### ISSUE TITLE
spring-cloud-gateway grpc supports H2C

### ISSUE THREAD

**Issue by jianmo1997** [Albertoimpl/spring-cloud-gateway-grpc#1]
First of all thank you very much for your reply before

Our business scenarios need to support non-SSL mode transmission,That means we need to support H2C

Could you give us some suggestions and tell us how to modify so that spring-cloud-gateway can support H2C?

Many thanks

**Comment by Albertoimpl** [comment]
Hey @jianmo1997 I recommend opening an issue in https://github.com/spring-cloud/spring-cloud-gateway so we can support both modes in the project.
It requires a few internal changes but it's definitely doable.
Thanks!

**Comment by jianmo1997** [comment]
Thank you, I will submit it right away
